### ISSUE TITLE
Document SHA512 support in CRMScript

### ISSUE THREAD

**Issue by digitaldiina** [SuperOfficeDocs/crmscript#13]
Add docs for a new method to support SHA512 in CRMScript

**Comment by kronicz** [comment]
@digitaldiina is this not covered in https://github.com/SuperOfficeDocs/crmscript/blob/13-add-sha512-support/docs/api-reference/global-functions/encodeHMACSHA512.md ?

**Comment by digitaldiina** [comment]
@kronicz yes it is covered. We're just waiting for the feature to be released before creating and approving the PR.

I merged main into the branch and added the file to the toc so atm it is good to go. 
I listed it in https://github.com/SuperOfficeDocs/superoffice-docs/issues/102 so we don't forget to add it to the release notes.
