### ISSUE TITLE
Create REST web services with CRMScripts

### ISSUE THREAD

**Issue by SuperOfficeDevNet** [SuperOfficeDocs/crmscript#14]
Please document the possibility to create REST web services using CRMScripts!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [into-to-superoffice-apis](https://github.com/SuperOfficeDocs/data-access/blob/main/docs/getting-started/index.md/#L1)

**Comment by digitaldiina** [comment]
@SuperOfficeDevNet I think the content is there, can we close this issue?:

https://docs.superoffice.com/automation/crmscript/persons-and-organizations/build-custom-rest-api-methods.html

![image](https://user-images.githubusercontent.com/23242792/151533420-b9e622d3-7a04-4d76-8213-ec62b92e1ba9.png)

crmscript\docs\persons-and-organizations\build-custom-rest-api-methods.md

**Comment by digitaldiina** [comment]
Discussed with @SuperOfficeDevNet and concluded that it is OK to close.
