### ISSUE TITLE
Feedback for ProjectMemberArray GetProjectMembers(Integer projectId)

### ISSUE THREAD

**Issue by ArildEik** [SuperOfficeDocs/crmscript#17]
I'm not an expert programmer in CRM Script, but as a C# programmer I don't understand why the doc says:

ProjectMemberArray res = agent.GetProjectMembers(projectId);

when the code that actually works in CRM Script is this:

NSProjectMember[] res = agent.GetProjectMembers(projectId); 

These "mistakes" is occuring all over the CRM Sctipt docs and is creating unecessary frustrations - at least for me

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [crmscript_ref_NSProjectAgent_GetProjectMembers](https://github.com/SuperOfficeDocs/crmscript/blob/main/docs/api-reference/classes/NSProjectAgent/GetProjectMembers.md/#L1)

**Comment by SuperOfficeDevNet** [comment]
This issue is the same, and being handled in issue #15
