### ISSUE TITLE
Improve TriggerScript documentation

### ISSUE THREAD

**Issue by SuperOfficeDevNet** [SuperOfficeDocs/crmscript#24]
There are several missing triggers definitions.

[TriggerScripts](https://github.com/SuperOfficeDocs/crmscript/tree/main/docs/api-reference/trigger-scripts)

There should be relevant docs for each event handler type:

- [x] 100. NewTicket
- [x] 101. NewTicketFromCustomerCenter
- [x] 102. NewTicketFromEmail
- [x] 103. NewTicketFromCustomerCenterBeforeSave
- [x] 104. NewTicketFromSpmLink
- [x] 105. NewNotifyTicketFromForm
- [x] 106. NewTicketFromForm
- [x] 109. TicketSave
- [x] 110. TicketClose
- [x] 111. TicketPostponed
- [x] 112. TicketDeleted
- [x] 113. TicketActivated
- [x] 120. TicketReopened
- [x] 121. TicketReopenedFromCustomerCenter
- [x] 122. TicketReopenedFromEmail
- [x] 140. TicketChangedPriority
- [x] 141. TicketChangedCategory
- [x] 142. TicketChangedOwnedBy
- [x] 143. TicketChangedPrimaryCustomer
- [x] 144. TicketChangedTicketStatus
- [x] 145. TicketChangedSlevel
- [x] 150. TicketMessageAdded
- [x] 151. TicketInternalMessageAdded
- [x] 152. TicketExternalMessageAdded
- [x] 153. TicketMessageSentimentCalculated
- [x] 200. CompactModeInjection
- [x] 210. CustomerCenterAuthentication
- [x] 300. ScheduledTaskFailed
- [x] 301. DbiTaskFailed
- [x] 302. CustomerSetSubscriptions
- [x] 303. ImportMailBeforeProcessing
- [x] 304. ImportMailAfterProcessing
- [x] 305. MainMenu
- [x] 400. ChatNewSession
- [x] 401. ChatSessionChangedStatus
- [x] 402. ChatBeforeSaveNewMessage
- [x] 403. ChatAfterSaveNewMessage
- [x] 500. ServiceScreenNewTicketLoad
- [x] 501. ServiceScreenNewQuickTicketLoad
- [x] 502. ServiceScreenListTicketMessagesLoad
- [x] 503. ServiceScreenAddMessageLoad
- [x] 504. ServiceScreenEditTicketLoad
- [x] 505. ServiceScreenViewCustomerLoad
- [x] 506. ServiceScreenEditCustomerLoad
- [x] 507. ServiceScreenViewCompanyLoad
- [x] 508. ServiceScreenEditCompanyLoad
- [x] 509. ServiceScreenForwardLoad
- [x] 510. ServiceScreenEditExtraTableLoad
- [x] 600. ServiceScreenNewTicketBeforeSubmit
- [x] 601. ServiceScreenNewQuickTicketBeforeSubmit
- [x] 602. ServiceScreenListTicketMessagesBeforeSubmit
- [x] 603. ServiceScreenAddMessageBeforeSubmit
- [x] 604. ServiceScreenEditTicketBeforeSubmit
- [x] 605. ServiceScreenViewCustomerBeforeSubmit
- [x] 606. ServiceScreenEditCustomerBeforeSubmit
- [x] 607. ServiceScreenViewCompanyBeforeSubmit
- [x] 608. ServiceScreenEditCompanyBeforeSubmit
- [x] 609. ServiceScreenForwardBeforeSubmit
- [x] 610. ServiceScreenEditExtraTableBeforeSubmit
- [x] 700. ServiceScreenNewTicketAfterSubmit
- [x] 701. ServiceScreenNewQuickTicketAfterSubmit
- [x] 702. ServiceScreenListTicketMessagesAfterSubmit
- [x] 703. ServiceScreenAddMessageAfterSubmit
- [x] 704. ServiceScreenEditTicketAfterSubmit
- [x] 705. ServiceScreenViewCustomerAfterSubmit
- [x] 706. ServiceScreenEditCustomerAfterSubmit
- [x] 707. ServiceScreenViewCompanyAfterSubmit
- [x] 708. ServiceScreenEditCompanyAfterSubmit
- [x] 709. ServiceScreenForwardAfterSubmit
- [x] 710. ServiceScreenEditExtraTableAfterSubmit
- [x] 1001. SalesBeforeSaveAppointment
- [x] 1002. SalesBeforeSaveStakeholder
- [x] 1003. SalesBeforeSaveQuote
- [x] 1004. SalesBeforeSaveDocument
- [x] 1005. SalesBeforeSaveContact
- [x] 1006. SalesBeforeSavePerson
- [x] 1007. SalesBeforeSaveRelation
- [x] 1008. SalesBeforeSaveSale
- [x] 1009. SalesBeforeSaveProject
- [x] 1010. SalesBeforeSaveSelection
- [x] 1011. SalesBeforeSaveProjectMember
- [x] 1012. SalesBeforeSaveSelectionMember
- [x] 1013. SalesBeforeSaveQuoteLine
- [x] 1101. SalesAfterSaveAppointment
- [x] 1102. SalesAfterSaveStakeholder
- [x] 1103. SalesAfterSaveQuote
- [x] 1104. SalesAfterSaveDocument
- [x] 1105. SalesAfterSaveContact
- [x] 1106. SalesAfterSavePerson	
- [x] 1107. SalesAfterSaveRelation	
- [x] 1108. SalesAfterSaveSale	
- [x] 1109. SalesAfterSaveProject
- [x] 1110. SalesAfterSaveSelection
- [x] 1111. SalesAfterSaveProjectMember
- [x] 1112. SalesAfterSaveSelectionMember
- [x] 1113. SalesAfterSaveQuoteLine

**Comment by digitaldiina** [comment]
@SuperOfficeDevNet, @kronicz: this list needs to be pruned to what's actually missing from [the reference](https://docs.superoffice.com/api/reference/crmscript/trigger-scripts/)
