### ISSUE TITLE
Missing correct return types on some CRMScript methods

### ISSUE THREAD

**Issue by kronicz** [SuperOfficeDocs/crmscript#34]
Example of class missing correct return type: WeekSchedule. 
![image](https://user-images.githubusercontent.com/8218051/132229692-65be5b95-530a-4b99-949b-484f0d687edc.png)

Correct return type in this instance is TimeSpan

Others with similar issue can be found using same structure in files.

**Comment by digitaldiina** [comment]
Closing this issue since it will be resolved by #9 (YAML format)
