### ISSUE TITLE
Feedback for Arrays

### ISSUE THREAD

**Issue by xt1** [SuperOfficeDocs/crmscript#74]
[Enter feedback here]
Feel like String and Integer data types should point to this array section.
I was looking for String arrays under the String data type, and there is nothing to point at the Array section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [crmscript_fundamentals_arrays](https://github.com/SuperOfficeDocs/crmscript/blob/main/docs/fundamentals/arrays.md/#L1)

**Comment by digitaldiina** [comment]
![image](https://user-images.githubusercontent.com/23242792/149482395-5e418fa9-476c-47c3-82f9-624d6cebd972.png)
