### ISSUE TITLE
'language' variable user not described correctly

### ISSUE THREAD

**Issue by acdavidh** [SuperOfficeDocs/crmscript#75]
The docs describe the language variable of the (CRMScript) user class to return a string with the language code, but it actually returns the language id, which is probably one of the following values:

Norwegian = 0,
English = 1,
German = 2,
Swedish = 3,
Danish = 4,
Dutch = 5,
French = 6,
Spanish = 7,
Italian = 8,
Czech = 9,
Finnish = 10,
Polish = 11,
Russian = 12,
Ukrainian = 13

Example;
```
User activeUser = getActiveUser();
print(activeUser.getValue("language"));
```

Mentioned here:
https://github.com/SuperOfficeDocs/crmscript/blob/415fd2d9b2891a8391ba2be23b439cd25ae39084/docs/api-reference/CRMScript.Native.User.yml#L42
https://github.com/SuperOfficeDocs/crmscript/blob/main/docs/persons-and-organizations/user.md/#L1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [crmscript_class_user](https://github.com/SuperOfficeDocs/crmscript/blob/main/docs/persons-and-organizations/user.md/#L1)

**Comment by digitaldiina** [comment]
We had a list of languages earlier. However, according to @kronicz this is not an enum but depends on the database. Could you please elaborate on this Michel?

**Comment by AnthonyYates** [comment]
It's an enum...

![image](https://user-images.githubusercontent.com/1012665/148065834-a08e19f8-cef2-455b-ac05-bcf854da633e.png)

**Comment by acdavidh** [comment]
The CRMScript User class reference also needs to be updated

https://github.com/SuperOfficeDocs/crmscript/blob/415fd2d9b2891a8391ba2be23b439cd25ae39084/docs/api-reference/CRMScript.Native.User.yml#L42

**Comment by digitaldiina** [comment]
@kronicz can you please update the reference too and submit a new PR? I've restored the branch so you can reuse that.

Thanks for pointing this out, @acdavidh :)
