### ISSUE TITLE
Add missing HtmlElement Enum for FieldType

### ISSUE THREAD

**Issue by SuperOfficeDevNet** [SuperOfficeDocs/crmscript#76]
Reference [this forum post](https://community.superoffice.com/no/forums/administrator-forums/setting-up-and-administrating-service/is-it-possible-to-have-a-conditional-field-in-a-ticket-header/) for context.

enum FieldType
  {
    FieldTypeDatabase = 1,
    FieldTypeStatic = 2,
    FieldTypeFunction = 3,    
    FieldTypeGroup = 4,
    FieldTypeBreak = 5,
    FieldTypeStatusMonitor = 6,
    FieldTypeElement = 7,
  }

**Comment by kronicz** [comment]
This only relates to https://github.com/SuperOfficeDocs/user-interface/blob/main/docs/service-ui/blogic-screen-elements/info-fields-2.md

**Comment by digitaldiina** [comment]
![image](https://user-images.githubusercontent.com/23242792/149471852-fe6f1664-1d23-4544-b4b9-0d920650479e.png)
